"""Add V2 progressive workflow fields

Revision ID: 9f53850aeeaa
Revises: 2e1f6f978680
Create Date: 2025-07-02 17:15:06.440622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f53850aeeaa'
down_revision: Union[str, Sequence[str], None] = '2e1f6f978680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('photo_id', sa.String(), nullable=False),
    sa.Column('stage_from', sa.String(), nullable=True),
    sa.Column('stage_to', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('app_used', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_actions_batch_id'), 'processing_actions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_processing_actions_photo_id'), 'processing_actions', ['photo_id'], unique=False)
    op.create_index(op.f('ix_processing_actions_stage_from'), 'processing_actions', ['stage_from'], unique=False)
    op.create_index(op.f('ix_processing_actions_stage_to'), 'processing_actions', ['stage_to'], unique=False)
    op.add_column('photos', sa.Column('processing_stage', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('priority_level', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('needs_attention', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_photos_needs_attention'), 'photos', ['needs_attention'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_needs_attention'), table_name='photos')
    op.drop_column('photos', 'needs_attention')
    op.drop_column('photos', 'priority_level')
    op.drop_column('photos', 'processing_stage')
    op.drop_index(op.f('ix_processing_actions_stage_to'), table_name='processing_actions')
    op.drop_index(op.f('ix_processing_actions_stage_from'), table_name='processing_actions')
    op.drop_index(op.f('ix_processing_actions_photo_id'), table_name='processing_actions')
    op.drop_index(op.f('ix_processing_actions_batch_id'), table_name='processing_actions')
    op.drop_table('processing_actions')
    # ### end Alembic commands ###
